# Generated by Django 5.1.1 on 2024-10-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Brand Name")),
                (
                    "headquarters",
                    models.CharField(
                        max_length=100, verbose_name="Headquarters Country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Model_Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Model Name")),
                ("year", models.IntegerField(verbose_name="Year of Issue")),
                (
                    "body_style",
                    models.CharField(max_length=100, verbose_name="Body Style"),
                ),
            ],
            options={
                "verbose_name": "Model",
                "verbose_name_plural": "Models",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("mileage", models.PositiveBigIntegerField(verbose_name="Mileage")),
                (
                    "exterior_color",
                    models.CharField(max_length=50, verbose_name="Exterior Color"),
                ),
                (
                    "interior_color",
                    models.CharField(max_length=50, verbose_name="Interior Color"),
                ),
                (
                    "fuel_type",
                    models.CharField(max_length=50, verbose_name="Fuel Type"),
                ),
                (
                    "transmission",
                    models.CharField(max_length=50, verbose_name="Transmission"),
                ),
                ("engine", models.CharField(max_length=50, verbose_name="Engine")),
                ("is_on_sale", models.BooleanField(verbose_name="Is on Sale")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.model_car",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
    ]
