# Generated by Django 5.1.1 on 2024-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_rename_headquarters_brand_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model_car",
            old_name="name",
            new_name="model_name",
        ),
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
    ]
