version: '3.9'


services:
  db:
    image: postgres
    container_name: car_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  web:
    build: .
    entrypoint: /docker-entrypoint.sh
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/car_api
    ports:
      - "8000:8000"
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - default
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

volumes:
  postgres_data:
    driver: local

networks:
  default: